server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/learn_it
    username: springstudent
    password: ${SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.insureflow.customer.dto.PolicyEvent
